### ISSUE TITLE
Need your guidance

### ISSUE THREAD

**Issue by ItzAmirreza** [katietheqt/curium#2]
Hey, This is not an issue, but rather me not understanding how exporting works.

Right now I implemented Fabric API as modImplementation in the gradle, so I can use some of its events. I did some modifications in the client, and now I want to export it as the jar file it needs to be and run it on a different machine. 

What exactly do I have to do? I did build and tried running with java [filename], tho that doesn't work & I know I'm doing something wrong since I don't have much experience with clients overall.

Would appreciate any help.

**Comment by ghost** [comment]
You have to build a JAR using Gradle (`./gradlew remapJar`) and then add it to the `mods` folder of a Minecraft instance.

**Comment by ItzAmirreza** [comment]
So from my understanding, curium is not a standalone client that can be run itself and needs to be put in the mods folder?

If yes, is it possible to make it standalone with the current system so it can be run like via console when exported?

**Comment by ghost** [comment]
Curium is a fabric mod that causes a standard client to not require LWJGL as it strips the rendering code. If you want to run it as a command line application I would suggest looking into command line MC launcher implementations.

https://github.com/katietheqt/cryocool may also be useful to you.
